### ISSUE TITLE
use Purge_Dups with ONT or Illumina reads

### ISSUE THREAD

**Issue by jazberna1** [dfguan/purge_dups#3]
Hello,

I see the pbfofn option in pd_config.py takes a list of pacbio file. I was wondering if ONT or Illumina are also valid techonolgies for Purge_Dups.

Many thanks
Jorge

**Comment by dfguan** [comment]
Hey Jorge, I didn't test purge_dups with ONT or Illumina short reads, but since purge_dups just uses raw sequencing reads for read depth calcuation, I think they may be usable as well.  You need to write a shell script to build purge_dups pipeline, you can follow my [pipeline guide](https://github.com/dfguan/purge_dups#pplg), for ONT data, please change the minimap2 mapping option from "map-pb" to "map-ont", and keep the other commands unchanged. For illumina reads, please use "bwa mem" with default settings for mapping and after you get the bams, use ngcstat (in bin directory) to calculate the read dept, and keep the other commands unchanged. Cheers, Dengfeng.

**Comment by andreaswallberg** [comment]
Thanks for the information!

Presumably the accuracy of the method increases with overall read depths, regardless of technology. I realise this is impossible to answer, but what minimum depths do you recommend to have decent success with this toolkit?

**Comment by jazberna1** [comment]
Hello Dengfeng,

Thanks so much. I'll have a go.
Jorge

**Comment by dfguan** [comment]
@andreaswallberg, that's right, with deeper sequencing, the results will be more reliable. I didn't test assembly with less than 50X, so ~50X I think.

**Comment by HenrivdGeest** [comment]
50x per haplotype or total coverage?

**Comment by dfguan** [comment]
for total coverage.
