### ISSUE TITLE
Why N's in purged.fa

### ISSUE THREAD

**Issue by cwb14** [dfguan/purge_dups#31]
Hi Dengfeng,

I noticed that purge_dups added 350 N-regions with 8,050 total N's to our final purged.fa. Could you explain these N-regions a bit? Is purge_dups breaking contigs and re-joining them with N's? From the manuscript, I see;

> We segment the input draft assembly into contigs by cutting at blocks ‘N’s, and use minimap2 to generate an all by all self-alignment.

I think purge_haplotigs doesn't add N's, so this seems to be one of the differentiating points between the two tools. Thank you!

**Comment by dfguan** [comment]
Hi, sorry for the late reply. Due to heterozygosity sometimes purge_dups may not be able to find a colinear match for a heterozygous region, illustrate in the sketch below, slash and backslash used to show different matches. the middle part in between the matches is heterzygous.  In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants.  

contig1 -----------------                      contig 1 ----------NNNN-----
                    /   /       \         \            ---->  
contig2      -------------------

Some of the middle N's may also be repeats. If you do not like the Ns in contigs, there is an `-e` option of `get_seq` to ignore removing those in the middle of a contig. If you still want to remove the middle sequences, you can also use `-s` to remove them and keep the remnants separated. 


Dengfeng.

**Comment by cwb14** [comment]
Got it! Thank you for the extra detail :)

Best,
Chris

**Comment by Tierhon** [comment]
Hi Dengfeng,
sorry for opening up an old issue.

What is the rational behind removing that heterozygous sequence? I think I very much would like to keep them.

Thank you.

Ole

**Comment by dfguan** [comment]
Hi Ole, 

Purge_dups is not removing heterozygous sequences, it is removing **redundant** heterozygous sequences, those heteryzygous sequences who should only appear once, but showed twice, these are the sequences purge_dups is purging. There are two reasons for doing this, firstly, we are aiming to create a primary (haploid) assembly, a haploid assembly should not contain duplicated heterozygous sequences; secondly, the existing heterozygous sequences in primary assembly will impair our further scaffolding processes.  

Best,

Dengfeng

**Comment by Tierhon** [comment]
Thank you, Dengfeng, but I was thinking especially on your answer above "In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants". From that example, it looks like you have two contigs where parts are collinear, while some are not. Further, you said "In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants". Does that mean joining contig1 and contig2 and inserting 23 Ns between them? 

I think I stated my question wrongly, I just want to understand a bit better what happens if I don't allow merging by inserting 23 Ns. Then I might have a bit less purged sequences, and a bit more duplications in my assembly? 

Some of the regions removed were several 100 kbps for my species, so I was unsure what was happening with that. (100s of kbp were replaced with 23 Ns.)

Thank you.

Ole

**Comment by dfguan** [comment]
Hi Ole,

Sorry for the late reply.

In this case, purge_dups will remove the matched regions in contig1 and put
> 23' Ns to join remnants


It means if purge_dups found a haplotypic duplication in the middle of a
contig, it will replace the duplication with 23 Ns. Sometimes this
operation is good, since not all haployptic duplication happens at the ends
of the contigs, but sometimes this can lead to overpurging. I need to do
more investigations on this.

If you do not like this function, purge_dups has added a switch to remove
the dupliations only at the ends of the contigs, you can open it with
"get_seqs -e dups.bed genome.fa", but this option will leave more
duplications in your assembly.

Hope this helps, for any other questions please let me know.

Best,


Dengfeng.

**Comment by Tierhon** [comment]
Hi Dengfeng.

Thank you for your answer, now I understand this better. Some of the stuff that gets removed are several hundred kbp large in my case, so I am a bit hesitant in removing that. 

Ole

**Comment by kuangtianhui** [comment]
> Hi, sorry for the late reply. Due to heterozygosity sometimes purge_dups may not be able to find a colinear match for a heterozygous region, illustrate in the sketch below, slash and backslash used to show different matches. the middle part in between the matches is heterzygous. In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants.
> Hi, due to heterozygosity sometimes purge_dups may not be able to find a colinear match for a heterozygous region, illustrate in the sketch below, slash and backslash used to show different matches. the middle part in between the matches is heterzygous. In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants.
> 
> ![image](https://user-images.githubusercontent.com/6100864/79042180-16b94c80-7c28-11ea-9cf6-1307eb3f7a69.png)
> 
> Some of the middle N's may also be repeats. If you do not like the Ns in contigs, there is an `-e` option of `get_seq` to ignore removing those in the middle of a contig. If you still want to remove the middle sequences, you can also use `-s` to remove them and keep the remnants separated.
> 
> Dengfeng.

Hi, Dr. Deng. happy new year. I tried to us

> Hi, sorry for the late reply. Due to heterozygosity sometimes purge_dups may not be able to find a colinear match for a heterozygous region, illustrate in the sketch below, slash and backslash used to show different matches. the middle part in between the matches is heterzygous. In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants.
> Hi, due to heterozygosity sometimes purge_dups may not be able to find a colinear match for a heterozygous region, illustrate in the sketch below, slash and backslash used to show different matches. the middle part in between the matches is heterzygous. In this case, purge_dups will remove the matched regions in contig1 and put 23' Ns to join remnants.
> 
> ![image](https://user-images.githubusercontent.com/6100864/79042180-16b94c80-7c28-11ea-9cf6-1307eb3f7a69.png)
> 
> Some of the middle N's may also be repeats. If you do not like the Ns in contigs, there is an `-e` option of `get_seq` to ignore removing those in the middle of a contig. If you still want to remove the middle sequences, you can also use `-s` to remove them and keep the remnants separated.
> 
> Dengfeng.

Hi, Dr. Deng, I want to try the "-e" option of get_seq. But it did't work. And it's error logs is that:"src/get_seqs: invalid option -- 'e'
[E::main] undefined option ?". Than I run "get_seq -h", it looks like the get_seq has no option of "-e". 

Usage: get_seqs  [<options>] <DUPs.BED> <FASTA> 
Options:
         -p    STR      prefix of output files [NULL]
         -c    BOOL     keep high coverage contigs in the primary contig set [FALSE]
         -a    BOOL     do not add prefix to haplotigs [FALSE]
         -l    INT      minimum primary contig length [1000]
         -m    INT      minimum ratio of remaining primary contig length to the original contig length [0.05]
         -h             help
My version is purge_dups-1.0.1. So is there any parameter to replace this "-e"?
Best wishes
Kuang Tian-hui
